# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 220)
        self.upload = QtWidgets.QPushButton(Form)
        self.upload.setGeometry(QtCore.QRect(40, 10, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.upload.setFont(font)
        self.upload.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.upload.setObjectName("upload")
        self.s_time = QtWidgets.QTimeEdit(Form)
        self.s_time.setGeometry(QtCore.QRect(40, 70, 71, 21))
        self.s_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.s_time.setObjectName("s_time")
        self.e_time = QtWidgets.QTimeEdit(Form)
        self.e_time.setGeometry(QtCore.QRect(40, 120, 71, 21))
        self.e_time.setObjectName("e_time")
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setGeometry(QtCore.QRect(40, 160, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.ok.setFont(font)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ok.setObjectName("ok")
        self.i_name = QtWidgets.QLabel(Form)
        self.i_name.setGeometry(QtCore.QRect(123, 32, 199, 16))
        self.i_name.setText("")
        self.i_name.setObjectName("i_name")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(120, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setText("")
        self.result.setTextFormat(QtCore.Qt.AutoText)
        self.result.setObjectName("result")
        self.o_name = QtWidgets.QLineEdit(Form)
        self.o_name.setGeometry(QtCore.QRect(120, 180, 201, 20))
        self.o_name.setObjectName("o_name")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 160, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(120, 10, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "视频剪辑"))
        self.upload.setText(_translate("Form", "上传视频"))
        self.s_time.setDisplayFormat(_translate("Form", "H:mm:ss"))
        self.e_time.setDisplayFormat(_translate("Form", "H:mm:ss"))
        self.ok.setText(_translate("Form", "开始剪辑"))
        self.label_2.setText(_translate("Form", "输出文件名："))
        self.label_1.setText(_translate("Form", "输入文件名："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
